# Generated by Django 5.2.12 on 2026-03-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#ffffff', max_length=7)),
                ('font_family', models.CharField(default='Arial', max_length=50)),
            ],
        ),
    ]
